### PR TITLE
Removing primary view switch in teleop Joints Jog

### PR DESCRIPTION
**Pull request by Hoffalypse**
This is a removal of two `switchUIPrimaryView' behaviors. They are both tied to the `RequestTeleoperation` subtree. They are being removed so that in multi pane view when moving the sliders the view does not jump back to the main pane.

### CODE REVIEW

**Comment by MikeWrock** [comment]
One thing I noticed when testing this out is the joint jog panel does not render over the BT pane, so if it is selected as the primary view then the joint jog panel does not appear. The previous requirement to change primary panes to Visualization masked this issue, but now it is not longer prevented.

I would say that the issue I noted is less painful than the panes jumping around on you, but I would like to hear @Hoffalypse thoughts on how we can either:
- Force the visualization pane to be primary **only** when the BT pane is currently the primary pane
- Render joint jog over the BT pane
- Pop a warning that joint jog is not shown when BT is the primary pane (and tell the user to change the primary pane to something else)

**Review by mewtwoshaurd — APPROVED** [review]
Played around with it, the sliders are kind of in the way of the robot but they don't jump around and the scene seems stable. Resized my window a few times too and had no issues

**Comment by Hoffalypse** [comment]
@MikeWrock This will be fixed in #9069. The pane will not jump but all functionality will be shown in the visualization pane no matter where it exists now. I think this creates the best UX as I generally feel the less jumping the better.

**Comment by Hoffalypse** [comment]
@mewtwoshaurd are you using a recent version of main. They shouldnt jump when switched anymore.

**Comment by mewtwoshaurd** [comment]
@Hoffalypse this is on the most recent main branch I just build:

https://github.com/user-attachments/assets/a4a1b06e-063d-4d7f-b802-e2c213e86b86

**Comment by Hoffalypse** [comment]
OK I may have spoke too soon, I apologize, it was in the merge Queue. Should be GTG now.

**Review by mewtwoshaurd — APPROVED** [review]
Double checked with new main and seems to work well -- I think I encountered a different UI bug that I'll make a ticket for, but these changes work

**Pull request merged**
