### PR TITLE
PickNik ur mujoco base config

### PR DESCRIPTION
**Pull request by MikeWrock**
3 blocks and a linear rail

### CODE REVIEW

**Comment by MikeWrock** [comment]
@nbbrooks just looking for some initial impressions here. I've noticed the pick object still generates a grasp pose with the wrong normal so I have to flip it around, and the UI saves waypoints with incorrect indentation so pre-commit fails.

Also, it likes to complain about a fixed joint publishing its joint_state, however when I make the robotiq finger joint continuous the MTC Execute task fails in Pick Object because it cannot claim the command interface

**Comment by nbbrooks** [comment]
Should I be able to run the `picknik_ur_mujoco_config` config with the 5.1.1 release? I tried and ros2 control had a bad time

```
drivers-1       | [ros2_control_node-2] [WARN] [1718112605.936336420] [controller_manager]: [Deprecated] Passing the robot description parameter directly to the control_manager node is deprecated. Use '~/robot_description' topic from 'robot_state_publisher' instead.
drivers-1       | [ros2_control_node-2] [INFO] [1718112605.936863064] [resource_manager]: Loading hardware 'ur_mujoco_control' 
drivers-1       | [ros2_control_node-2] terminate called after throwing an instance of 'pluginlib::LibraryLoadException'
drivers-1       | [ros2_control_node-2]   what():  According to the loaded plugin descriptions the class picknik_mujoco_ros/MujocoSystem with base class type hardware_interface::SystemInterface does not exist. Declared types are  fake_components/GenericSystem mock_components/GenericSystem robotiq_driver/RobotiqGripperHardwareInterface test_hardware_components/TestSystemCommandModes test_hardware_components/TestTwoJointSystem test_system test_unitilizable_system ur_robot_driver/URPositionHardwareInterface
drivers-1       | [ros2_control_node-2] Stack trace (most recent call last):
drivers-1       | [ros2_control_node-2] #16   Object "", at 0xffffffffffffffff, in 
drivers-1       | [ros2_control_node-2] #15   Object "/opt/ros/humble/lib/controller_manager/ros2_control_node", at 0x6340fbf80d84, in 
drivers-1       | [ros2_control_node-2] #14   Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x737e79d64e3f, in __libc_start_main
drivers-1       | [ros2_control_node-2] #13   Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x737e79d64d8f, in 
drivers-1       | [ros2_control_node-2] #12   Object "/opt/ros/humble/lib/controller_manager/ros2_control_node", at 0x6340fbf8089e, in 
drivers-1       | [ros2_control_node-2] #11   Object "/opt/ros/humble/lib/libcontroller_manager.so", at 0x737e7a459da9, in controller_manager::ControllerManager::ControllerManager(std::shared_ptr<rclcpp::Executor>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::NodeOptions const&)
drivers-1       | [ros2_control_node-2] #10   Object "/opt/ros/humble/lib/libcontroller_manager.so", at 0x737e7a4555ef, in controller_manager::ControllerManager::init_resource_manager(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
drivers-1       | [ros2_control_node-2] #9    Object "/opt/ros/humble/lib/libhardware_interface.so", at 0x737e79c67d9d, in hardware_interface::ResourceManager::load_urdf(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool)
drivers-1       | [ros2_control_node-2] #8    Object "/opt/ros/humble/lib/libhardware_interface.so", at 0x737e79c661ce, in 
drivers-1       | [ros2_control_node-2] #7    Object "/opt/ros/humble/lib/libhardware_interface.so", at 0x737e79c4732a, in 
drivers-1       | [ros2_control_node-2] #6    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x737e7a0344d7, in __cxa_throw
drivers-1       | [ros2_control_node-2] #5    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x737e7a034276, in std::terminate()
drivers-1       | [ros2_control_node-2] #4    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x737e7a03420b, in 
drivers-1       | [ros2_control_node-2] #3    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x737e7a028b9d, in 
drivers-1       | [ros2_control_node-2] #2    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x737e79d637f2, in abort
drivers-1       | [ros2_control_node-2] #1    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x737e79d7d475, in raise
drivers-1       | [ros2_control_node-2] #0    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x737e79dd19fc, in pthread_kill
drivers-1       | [ros2_control_node-2] Aborted (Signal sent by tkill() 91 1000)
drivers-1       | [ERROR] [ros2_control_node-2]: process has died [pid 91, exit code -6, cmd '/opt/ros/humble/lib/controller_manager/ros2_control_node --ros-args --params-file /tmp/launch_params_ks1gb0vb --params-file /tmp/launch_params_h7ukod4f --params-file /home/nbb/user_ws/install/picknik_ur_mujoco_config/share/picknik_ur_mujoco_config/config/control/picknik_ur.ros2_control.yaml --params-file /tmp/launch_params_3b503mlx --params-file /tmp/launch_params_pkbvlkpo'].
```

**Comment by nbbrooks** [comment]
I am able to run this on 5.3 rc1 except the waypoints file is failing to parse. I'll upload screenshots in a bit.

**Comment by MikeWrock** [comment]
@nbbrooks can I get another review here?

Some things to take a look at or try:

- Pick April Tag Labelled Object
  - Looks for april tags, if one is found it will plan a path and provide a preview. If accepted, the motion is exectued
- Pick Cube
  - Prompts user to click cube location, adjust pose with iMarker, then previews and executes the motion
- Objective Comments
  - I don't know if they help or hurt here, so please take a peek at the objectives and subtrees of the objectives above

**Comment by nbbrooks** [comment]
- Can we change the initial positions of the arm so it is viewing the table or at least not flopped over on its side? It would be good to save that Home position as a waypoint as well
- 3 Waypoints Pick and Place is favorited and fails because no waypoints exist. Some ideas
  - Unfavorite it
  - Per Ezra's thread, delete 3 wp pnp from base_config and add it to site configs where it is actually useful (maybe just mock_sim)
  - Add some waypoints to the file

**Comment by nbbrooks** [comment]
I am also getting endless warning spam for
```
agent_bridge-1  | [move_group-1] [WARN] [1719585920.940272348] [move_group.moveit.get_urdf_service]: No kinematics plugin defined for group 'gripper'. Determining base and tip frames with the joint model group!
agent_bridge-1  | [move_group-1] [WARN] [1719585920.940310029] [move_group.moveit.get_urdf_service]: No kinematics plugin defined for group 'linear_actuator'. Determining base and tip frames with the joint model group!
```

**Review by sjahr — COMMENTED** [review]
Just tried this and I am getting this error:

```
studio-user@hedgehog:~/user_ws$ agent_robot.app
[INFO] [launch]: All log files can be found below /home/studio-user/.ros/log/2024-07-04-13-53-07-912570-hedgehog-12583
[INFO] [launch]: Default logging verbosity is set to INFO
Replacing ${UR_HARDWARE_TYPE:-ur5e} with ur5e
Replacing ${MOCK_HARDWARE:-true} with true
Traceback (most recent call last):
  File "/opt/overlay_ws/build/moveit_studio_utils_py/src/moveit_studio_utils_py/create_urdf.py", line 74, in create_xml_from_xacro
    robot_description_config = xacro.process_file(
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/xacro/__init__.py", line 1098, in process_file
    process_doc(doc, **kwargs)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/xacro/__init__.py", line 1050, in process_doc
    eval_all(doc.documentElement, macros, symbols)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/xacro/__init__.py", line 977, in eval_all
    elif handle_macro_call(node, macros, symbols):
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/xacro/__init__.py", line 824, in handle_macro_call
    eval_all(body, scoped_macros, scoped_symbols)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/xacro/__init__.py", line 977, in eval_all
    elif handle_macro_call(node, macros, symbols):
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/xacro/__init__.py", line 788, in handle_macro_call
    raise XacroException("Invalid parameter \"%s\"" % str(name), macro=m)
xacro.XacroException: Invalid parameter "parent"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ros/humble/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.18.9', 'console_scripts', 'ros2')())
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2cli/cli.py", line 91, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2launch/command/launch.py", line 172, in main
    return launch_a_launch_file(
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2launch/api/api.py", line 185, in launch_a_launch_file
    ret = launch_service.run()
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_service.py", line 375, in run
    return loop.run_until_complete(run_async_task)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_service.py", line 336, in run_async
    raise completed_tasks_exceptions[0]
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_service.py", line 230, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_service.py", line 250, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/actions/include_launch_description.py", line 164, in execute
    launch_description.get_launch_arguments_with_include_launch_description_actions())
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_description.py", line 161, in get_launch_arguments_with_include_launch_description_actions
    process_entities(self.entities, _conditional_inclusion=conditional_inclusion)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_description.py", line 152, in process_entities
    entity.describe_sub_entities(),
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/action.py", line 93, in describe_sub_entities
    return self.get_sub_entities() if self.condition is None else []
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/actions/include_launch_description.py", line 128, in get_sub_entities
    ret = self.__launch_description_source.try_get_launch_description_without_context()
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_description_source.py", line 69, in try_get_launch_description_without_context
    return self._get_launch_description(expanded_location)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_description_sources/any_launch_description_source.py", line 53, in _get_launch_description
    return get_launch_description_from_any_launch_file(location)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 54, in get_launch_description_from_any_launch_file
    return loader(launch_file_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_description_sources/python_launch_file_utilities.py", line 68, in get_launch_description_from_python_launch_file
    return getattr(launch_file_module, 'generate_launch_description')()
  File "/opt/overlay_ws/install/moveit_studio_agent/share/moveit_studio_agent/launch/robot_drivers.launch.py", line 16, in generate_launch_description
    system_config_parser = SystemConfigParser()
  File "/opt/overlay_ws/build/moveit_studio_utils_py/src/moveit_studio_utils_py/system_config.py", line 131, in __init__
    self.__urdf_xml = create_xml_from_xacro(robot_description_params, "urdf")
  File "/opt/overlay_ws/build/moveit_studio_utils_py/src/moveit_studio_utils_py/create_urdf.py", line 79, in create_xml_from_xacro
    raise XacroGenerationException from error
moveit_studio_utils_py.create_urdf.XacroGenerationException
```

**Review by sjahr — DISMISSED** [review]

**Review by dyackzan — APPROVED** [review]
@pac48 and I have preferred using the auto-generated urdf to reduce complexity here, and that's the way I've documented transferring a site config to a mujoco config in [this PR](https://github.com/PickNikRobotics/moveit_studio/pull/7578). This makes matching things between the mjcf and the urdf a lot easier. I've made a commit to that effect and added it on this PR. I'm OK reverting that commit if anyone feels very strongly about using xacro macros here

**Pull request merged**
