### PR TITLE
Top level launchfile

### PR DESCRIPTION
**Pull request by tylerjw**
fixes https://github.com/PickNikRobotics/moveit_studio/issues/6424

### CODE REVIEW

**Comment by Abishalini** [comment]
Should this be added to core Pro? So that this launch file can be used with all configs and not just UR mock hw

**Comment by tylerjw** [comment]
I don't think it should be in the studio repo (even though it obviously could be) as this is meant to be an entry-point for users to modify and add their launch details to this launchfile.

**Comment by Abishalini** [comment]
Shoot I forgot we are trying to remove launch files out of core studio. 
Can this be moved to `picknik_ur_base_config` so all the configs that inherit from it can use this launch file?

**Review by sea-bass — APPROVED** [review]

**Review by sea-bass — CHANGES_REQUESTED** [review]
Sorry, I just saw @Abishalini 's comment and agree with it.

**Comment by tylerjw** [comment]
This is your playground now, do whatever you want.

**Review by sea-bass — APPROVED** [review]

**Pull request merged**
